version: '2'
services:
  odsapigatewayexternals-app:
    image: odsapigatewayexternals
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://odsapigatewayexternals-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=OdsApiGatewayExternals
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8380:8380
  odsapigatewayexternals-mongodb:
    extends:
      file: mongodb.yml
      service: odsapigatewayexternals-mongodb
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
